name: soulpot
description: An application to control your connected plant with a SoulPot Analyzer.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: ">=2.16.2 <=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  google_sign_in: ^5.3.3
  auth_buttons: ^3.0.0
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  page_transition: ^2.0.9
  flutter_facebook_auth: ^3.5.0
  flutter_blue_plus: ^1.1.3
  wifi_scan: ^0.3.0
  loading_animation_widget: ^1.2.0+2
  im_stepper: ^1.0.1+1
  sizer: ^2.0.15
  firebase_analytics: ^9.1.10
  firebase_crashlytics: ^2.8.2
  cloud_firestore: ^3.1.18
  page_view_indicators: ^2.0.0
  cached_network_image: ^3.2.1
  firebase_messaging: ^11.4.2
  shared_preferences: ^2.0.15
  device_info_plus: ^4.0.0
  mqtt_client: ^9.6.8
  carousel_slider: ^4.1.1
  flutter_local_notifications: 9.6.1


dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

  lints: ^2.0.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/SoulPotLogoFlower.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Greenhouse
      fonts:
        - asset: assets/fonts/Greenhouse-Regular.otf
          style: normal

    - family: SoulPot
      fonts:
        - asset: assets/fonts/SoulPot.ttf

